version: '3.8'

services:
  app:
    build: .
    container_name: go-html-to-pdf
    ports:
      - "8080:8080"
    volumes:
      - ./pdfs:/app/pdfs
      - ./templates:/app/templates
    depends_on:
      - gotenberg
    environment:
      - GOTENBERG_URL=http://gotenberg:3000

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    ports:
      - "3000:3000" 